# Generated by Django 3.2.16 on 2024-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSupplierBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(verbose_name='Код товара от поставщика в 1С')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('brand', models.CharField(max_length=256, verbose_name='Бренд')),
                ('subgroup', models.CharField(max_length=256, verbose_name='Подгруппа')),
                ('supplier', models.SmallIntegerField(verbose_name='Код поставщика в 1С')),
            ],
            options={
                'verbose_name': 'код поставщика 1с',
                'verbose_name_plural': 'Коды поставщиков 1с',
            },
        ),
        migrations.CreateModel(
            name='CodeSupplierFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(verbose_name='Код товара от поставщика в 1С')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('brand', models.CharField(max_length=256, verbose_name='Бренд')),
                ('subgroup', models.CharField(max_length=256, verbose_name='Подгруппа')),
                ('supplier', models.SmallIntegerField(verbose_name='Код поставщика в 1С')),
                ('product_summary', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('size', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'код поставщика в файле',
                'verbose_name_plural': 'Коды поставщиков в файле',
            },
        ),
    ]
